//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genres
    {
        public Genres()
        {
            this.Movies = new HashSet<Movies>();
        }
    
        public long GenreID { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<Movies> Movies { get; set; }
    }
}
