//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public long MovieID { get; set; }
        public string Title { get; set; }
        public Nullable<long> Genre { get; set; }
        public string Director { get; set; }
        public Nullable<int> ReviewRating { get; set; }
        public Nullable<long> MPAARating { get; set; }
        public Nullable<int> YearReleased { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual Mpaa Mpaa { get; set; }
    }
}
